// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/openticket.proto

package openticketpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenTicket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Supply    string `protobuf:"bytes,1,opt,name=supply,proto3" json:"supply,omitempty"`
	UnitPrice string `protobuf:"bytes,2,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	Minted    bool   `protobuf:"varint,3,opt,name=minted,proto3" json:"minted,omitempty"`
}

func (x *OpenTicket) Reset() {
	*x = OpenTicket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_openticket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTicket) ProtoMessage() {}

func (x *OpenTicket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openticket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTicket.ProtoReflect.Descriptor instead.
func (*OpenTicket) Descriptor() ([]byte, []int) {
	return file_proto_openticket_proto_rawDescGZIP(), []int{0}
}

func (x *OpenTicket) GetSupply() string {
	if x != nil {
		return x.Supply
	}
	return ""
}

func (x *OpenTicket) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *OpenTicket) GetMinted() bool {
	if x != nil {
		return x.Minted
	}
	return false
}

type GetOpenTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetOpenTicketRequest) Reset() {
	*x = GetOpenTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_openticket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpenTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenTicketRequest) ProtoMessage() {}

func (x *GetOpenTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openticket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenTicketRequest.ProtoReflect.Descriptor instead.
func (*GetOpenTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_openticket_proto_rawDescGZIP(), []int{1}
}

func (x *GetOpenTicketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetOpenTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SetOpenTicketResponse) Reset() {
	*x = SetOpenTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_openticket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOpenTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOpenTicketResponse) ProtoMessage() {}

func (x *SetOpenTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openticket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOpenTicketResponse.ProtoReflect.Descriptor instead.
func (*SetOpenTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_openticket_proto_rawDescGZIP(), []int{2}
}

func (x *SetOpenTicketResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_openticket_proto protoreflect.FileDescriptor

var file_proto_openticket_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x22, 0x5a, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x6e,
	0x69, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x6e, 0x69, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x74, 0x65, 0x64,
	0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x4f,
	0x70, 0x65, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x32, 0xaa, 0x01, 0x0a, 0x11, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4f, 0x70,
	0x65, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x20, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x4a, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x21, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x33,
	0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x61,
	0x65, 0x6a, 0x61, 0x6e, 0x2f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x5f, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x3b, 0x6f, 0x70, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_openticket_proto_rawDescOnce sync.Once
	file_proto_openticket_proto_rawDescData = file_proto_openticket_proto_rawDesc
)

func file_proto_openticket_proto_rawDescGZIP() []byte {
	file_proto_openticket_proto_rawDescOnce.Do(func() {
		file_proto_openticket_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_openticket_proto_rawDescData)
	})
	return file_proto_openticket_proto_rawDescData
}

var file_proto_openticket_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_openticket_proto_goTypes = []interface{}{
	(*OpenTicket)(nil),            // 0: openticket.OpenTicket
	(*GetOpenTicketRequest)(nil),  // 1: openticket.GetOpenTicketRequest
	(*SetOpenTicketResponse)(nil), // 2: openticket.SetOpenTicketResponse
}
var file_proto_openticket_proto_depIdxs = []int32{
	1, // 0: openticket.OpenTicketService.GetOpenTicket:input_type -> openticket.GetOpenTicketRequest
	0, // 1: openticket.OpenTicketService.SetOpenTicket:input_type -> openticket.OpenTicket
	0, // 2: openticket.OpenTicketService.GetOpenTicket:output_type -> openticket.OpenTicket
	2, // 3: openticket.OpenTicketService.SetOpenTicket:output_type -> openticket.SetOpenTicketResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_openticket_proto_init() }
func file_proto_openticket_proto_init() {
	if File_proto_openticket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_openticket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenTicket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_openticket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOpenTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_openticket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOpenTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_openticket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_openticket_proto_goTypes,
		DependencyIndexes: file_proto_openticket_proto_depIdxs,
		MessageInfos:      file_proto_openticket_proto_msgTypes,
	}.Build()
	File_proto_openticket_proto = out.File
	file_proto_openticket_proto_rawDesc = nil
	file_proto_openticket_proto_goTypes = nil
	file_proto_openticket_proto_depIdxs = nil
}
